.TH JOSM 1 "December 26, 2012"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
josm \- Java OpenStreetMap Editor
.SH SYNOPSIS
.B josm
.SH DESCRIPTION
.B josm 
is an extensible editor for OpenStreetMap written in Java 6.
.PP
\fBOpenStreetMap\fR is a project aimed squarely at creating and providing
free geographic data such as street maps to anyone who wants them. It
allows you to view, edit and use geographical data in a collaborative way
from anywhere on Earth.
.PP
The project was started because most maps you think of as free actually
have legal or technical restrictions on their use, holding back people
from using them in creative, productive or unexpected ways.
.SH OPTIONS
.TP
.B \-h, \-?, \-\-help
Show help.
.TP
.B \-\-version
Display the JOSM version and exit.
.TP
\fB\-\-geometry=\fIwidth\fBx\fIheight\fB(+|-)x(+|-)y\fR
Standard X geometry argument.
.TP
\fB[\-\-download=]\fIminlat\fB,\fIminlon\fB,\fImaxlat\fB,maxlon\fR
Download the bounding box.
.TP
\fB[\-\-download=]\fIurl\fR
Download the location at the url (with lat=x&lon=y&zoom=z).
.TP
\fB[\-\-download=]\fIfilename\fR
Open a file (any filetype that can be opened with File/Open from the GUI).
.TP
\fB\-\-downloadgps=\fIminlat\fB,\fIminlon\fB,\fImaxlat\fB,\fImaxlon\fR
Download the bounding box as raw GPS.
.TP
\fB\-\-selection=\fIsearchstring\fR
Select with the given search.
.TP
.B \-\-[no\-]maximize
Launch in maximized (or minimized) mode.
.TP
.B \-\-reset\-preferences
Reset the preferences to the default.
.TP
\fB\-\-load\-preferences=\fIurl\fR
Load preferences from the given \fIurl\fR (in XML format).
.TP
\fB\-\-set=\fIkey\fB=\fIvalue\fR
Set the preference \fIkey\fR to \fIvalue\fR.
.TP
\fB\-\-language=\fIlanguage\fR
Set the language.
.SH JAVA PROPERTIES
The following options can be set by using Java system properties (i.e. -Dkey=value
passed to \fBjava\fR, or specified inside \fBJAVA_OPTS\fR).
.TP
\fBjosm.home=\fIpath\fR
Set the JOSM home directory to \fIpath\fR. This will contain all user settings.
Default is \fI~/.josm/\fR.
.SH ENVIRONMENT
.IP JAVA_HOME
Specify an alternate Java environment.
.IP JAVA_OPTS
Specify Java options.
For example, to use a HTTP proxy server with this program, set this environment variable
to something like \fIJAVA_OPTS="-Dhttp.proxyHost=yourProxyURL"\fR before starting josm.
.SH AUTHOR
josm was written by Immanuel Scholz.
The current maintainer is Dirk Stöcker.
.PP
This manual page was written by Andreas Putzo <andreas@putzo.net> and David Paleino
<dapal@debian.org>, and is licensed under the same terms of JOSM itself (currently,
the GNU General Public License, version 3 or later).
