
## Make it so config files are not overwritten
config() {
  NEW="$1"
  OLD="`dirname $NEW`/`basename $NEW .new`"
  # If there's no config file by that name, mv it over
  if [ ! -r $OLD ]; then
    mv $NEW $OLD
  elif [ "`cat $OLD | md5sum`" = "`cat $NEW | md5sum`" ]; then # toss the redundant copy
    rm $NEW
  fi
  # Otherwise, we leave the .new copy for the admin to consider...
}

## List of conf files to check
config etc/apache-tomcat/context.xml.new
config etc/apache-tomcat/logging.properties.new
config etc/apache-tomcat/catalina.policy.new
config etc/apache-tomcat/catalina.properties.new
config etc/apache-tomcat/server.xml.new
config etc/apache-tomcat/tomcat-java.conf.new
config etc/apache-tomcat/tomcat-users.xml.new
config etc/apache-tomcat/web.xml.new
config etc/rc.d/rc.tomcatd.new

## Check if group and/or user exists
check_env() {
  TOMCAT_USER=tomcat
  TOMCAT_GROUP=tomcat
  TOMCAT_UID=232
  TOMCAT_GID=232
  TOMCAT_HOME="/usr/share/apache-tomcat"

  grep -q "^$TOMCAT_GROUP:" /etc/group || groupadd -g $TOMCAT_GID $TOMCAT_GROUP || exit 1
  grep -q "^$TOMCAT_USER:" /etc/passwd || useradd -u $TOMCAT_UID -d $TOMCAT_HOME -m -k /dev/null -g $TOMCAT_GROUP $TOMCAT_USER || exit 1
}

check_env

chmod 0744 /usr/share/apache-tomcat/bin/*.sh
chmod 0700 /var/tmp/apache-tomcat

chown -fR tomcat.tomcat /etc/apache-tomcat
chown -fR tomcat.tomcat /usr/share/apache-tomcat
chown -fR tomcat.tomcat /var/cache/apache-tomcat
chown -fR tomcat.tomcat /var/lib/apache-tomcat
chown -fR tomcat.tomcat /var/log/apache-tomcat
chown -fR tomcat.tomcat /var/tmp/apache-tomcat

## Make symlinks (generated by makepkg)
